Events.on(ClientLoadEvent, () => {
    const halta = new Planet("halta", Planets.sun, 3, 1.2;
    halta.generator = new SerpuloPlanetGenerator();
    halta.mesh = new HexMesh(sarpa, 2);
    halta.orbitRadius = 4.75;
    halta.orbitTime = 1075
    halta.rotateTime = 360;
    halta.bloom = false;
    halta.radius = 0.87;
    halta.accessible = false;
    halta.hasAtmosphere = true;
    halta.atmosphereColor = Color.valueOf("caeded");
    halta.atmosphereRadIn = 0.82;
    halta.atmosphereRadOut = 0.825;
    halta.localizedName = "halta";
